// flow-typed signature: 94878323f272cb0dc8674567f569f77f
// flow-typed version: <<STUB>>/@firebase/firestore_v^3.4.9/flow_v0.163.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@firebase/firestore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@firebase/firestore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@firebase/firestore/dist/index.esm2017' {
  declare module.exports: any;
}

declare module '@firebase/firestore/dist/index.esm5' {
  declare module.exports: any;
}

declare module '@firebase/firestore/dist/index.node.cjs' {
  declare module.exports: any;
}

declare module '@firebase/firestore/dist/index.rn' {
  declare module.exports: any;
}

declare module '@firebase/firestore/dist/lite/index.browser.esm2017' {
  declare module.exports: any;
}

declare module '@firebase/firestore/dist/lite/index.browser.esm5' {
  declare module.exports: any;
}

declare module '@firebase/firestore/dist/lite/index.node.cjs' {
  declare module.exports: any;
}

declare module '@firebase/firestore/dist/lite/index.rn.esm2017' {
  declare module.exports: any;
}

// Filename aliases
declare module '@firebase/firestore/dist/index.esm2017.js' {
  declare module.exports: $Exports<'@firebase/firestore/dist/index.esm2017'>;
}
declare module '@firebase/firestore/dist/index.esm5.js' {
  declare module.exports: $Exports<'@firebase/firestore/dist/index.esm5'>;
}
declare module '@firebase/firestore/dist/index.node.cjs.js' {
  declare module.exports: $Exports<'@firebase/firestore/dist/index.node.cjs'>;
}
declare module '@firebase/firestore/dist/index.rn.js' {
  declare module.exports: $Exports<'@firebase/firestore/dist/index.rn'>;
}
declare module '@firebase/firestore/dist/lite/index.browser.esm2017.js' {
  declare module.exports: $Exports<'@firebase/firestore/dist/lite/index.browser.esm2017'>;
}
declare module '@firebase/firestore/dist/lite/index.browser.esm5.js' {
  declare module.exports: $Exports<'@firebase/firestore/dist/lite/index.browser.esm5'>;
}
declare module '@firebase/firestore/dist/lite/index.node.cjs.js' {
  declare module.exports: $Exports<'@firebase/firestore/dist/lite/index.node.cjs'>;
}
declare module '@firebase/firestore/dist/lite/index.rn.esm2017.js' {
  declare module.exports: $Exports<'@firebase/firestore/dist/lite/index.rn.esm2017'>;
}
